[package]
name = "cumulus_sync"
version = "0.1.0"
authors = ["Egor Berezovskiy <egor.neon@gmail.com>"]

[dependencies]
notify = "4.0.3"
walkdir = "2.1.4"
structopt = "0.2.7"
structopt-derive = "0.2.8"
reqwest = "0.8.5"
serde = "1.0.52"
serde_derive = "1.0.38"
serde_json = "1.0.14"
error-chain = "0.11.0"
uuid = { version = "0.6.3", features = ["serde", "v4"] }
chrono = { version = "0.4.2", features = ["serde"] }
