[package]
name = "cumulus_sync"
version = "0.1.0"
authors = ["Egor Berezovskiy <egor.neon@gmail.com>"]

[dependencies]
notify = "4.0.3"
walkdir = "2.0.1"
structopt = "0.1.6"
structopt-derive = "0.1.6"
reqwest = "0.8.4"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
error-chain = "0.11.0"
